### ISSUE TITLE
SetDrawBlendMode and SetDrawBright Support

### ISSUE THREAD

**Issue by gemayue** [Muratam/CCDxLib72#3]
It would be good if CCDxLib72 support SetDrawBlendMode SetDrawBright 
Thanks for you much for the CCDxLib72! It is really useful and saved me lot of time :)

**Comment by Muratam** [comment]
Thank you for using CCDxLib72, gemayue !
As you say, it would be good if these functions are implemented !
Unfortunately, because I am busy recently, It may take a lot of time... 
(if you implement these and make pull request, I'll marge it with pleasure !!)

**Comment by gemayue** [comment]
Thanks for the reply!
I am currently trying to improve CCDxLib72. I already made SetDrawBright and SetDrawBlendMode (Just the alpha part)

However I found that the DeleteGraph cannot delete the graph created with DerivationGraph. It seems delete the Src Graph instead. The Ram is not freed too. Some advice would be nice.Thanks!
